name: hard
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  - cudatoolkit=11.6
  - pip
  - pip:
    - mmcv>=2.0.0
    - mmsegmentation>=1.0.0
    - mmengine>=0.8.0
    - opencv-python>=4.5.0
    - numpy>=1.21.0
    - pandas>=1.3.0
    - scikit-image>=0.19.0
    - slidingwindow>=0.0.13
    - Pillow>=8.0.0
    - matplotlib>=3.5.0

